# Generated by Django 4.2.4 on 2023-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_calorie_profile_exercise_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calorie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exercise',
            field=models.FloatField(blank=True, choices=[(1.2, 'Sedentary'), (1.375, 'Lightly active'), (1.55, 'Moderately active'), (1.725, 'Very active'), (1.9, 'Super active')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
