# Generated by Django 4.2.4 on 2023-08-30 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_age_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
