# Generated by Django 4.2.4 on 2023-08-30 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=12, null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
