# Generated by Django 4.2.4 on 2023-08-30 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.IntegerField(blank=True, choices=[(-100, 'Light weight loss'), (-200, 'Moderately weight loss'), (-300, 'Extreme weight loss'), (0, 'Maintain Weight'), (100, 'Light weight gain'), (200, 'Moderate weight gain'), (300, 'Extreme weight gain')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calorie',
            field=models.IntegerField(blank=True, null=True, verbose_name='in kcal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(55), django.core.validators.MaxValueValidator(250)], verbose_name='in cm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='in kg'),
        ),
    ]
