# Generated by Django 4.2.4 on 2023-08-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_calorie_alter_profile_calorie_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 0), ('Female', 1)], max_length=50, null=True),
        ),
    ]
