# Generated by Django 4.2.4 on 2023-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.IntegerField(blank=True, choices=[(-500, 'Extreme weight loss'), (-300, 'Moderate weight loss'), (-250, 'Light weight loss'), (0, 'Maintain Weight'), (250, 'Light weight gain'), (300, 'Moderate weight gain'), (500, 'Extreme weight gain')], null=True),
        ),
    ]
