# Generated by Django 4.2.4 on 2023-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.IntegerField(blank=True, choices=[(-1000, 'Extreme weight loss'), (-500, 'Moderate weight loss'), (-250, 'Light weight loss'), (0, 'Maintain Weight'), (250, 'Light weight gain'), (500, 'Moderate weight gain'), (1000, 'Extreme weight gain')], null=True),
        ),
    ]
