# Generated by Django 4.2.4 on 2023-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.FloatField(blank=True, choices=[(-1000.0, 'Extreme weight loss'), (-500.0, 'Moderate weight loss'), (-250.0, 'Light weight loss'), (0.0, 'Maintain Weight'), (250.0, 'Light weight gain'), (500.0, 'Moderate weight gain'), (1000.0, 'Extreme weight gain')], null=True),
        ),
    ]
