# Generated by Django 4.2.4 on 2023-08-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_profile_calorie_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
