# Generated by Django 4.2.4 on 2023-09-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_remove_profile_calorie_consumed'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
