# Generated by Django 4.2.4 on 2023-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networksearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='request',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Pending'), (1, 'Accepted')], default=-1),
        ),
    ]
