# Generated by Django 4.2.4 on 2023-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_network_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='request',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted')], default=0),
        ),
    ]
