# Generated by Django 4.2.4 on 2023-08-31 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Calories in kcal'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Carbs in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Fats in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Proteins in grams'),
        ),
    ]
