# Generated by Django 4.2.4 on 2023-08-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_profile_preference'),
        ('food', '0016_alter_food_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
