# Generated by Django 4.2.4 on 2023-09-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_foodsearch_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsearch',
            name='created_at',
        ),
    ]
