# Generated by Django 4.2.4 on 2023-09-06 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_remove_profile_calorie_consumed'),
        ('food', '0022_alter_foodsearch_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Created At')),
                ('calorie_consumed', models.IntegerField(verbose_name='Calories consumed in kcal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
