# Generated by Django 4.2.4 on 2023-09-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_remove_profile_calorie_consumed'),
        ('food', '0023_usermetrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMetrics',
            new_name='UserMetric',
        ),
        migrations.RenameField(
            model_name='usermetric',
            old_name='calorie_consumed',
            new_name='calories_consumed',
        ),
    ]
