# Generated by Django 4.2.4 on 2023-09-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_rename_usermetrics_usermetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetric',
            name='calories_consumed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calories consumed in kcal'),
        ),
    ]
