# Generated by Django 4.2.4 on 2023-09-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_alter_usermetric_calories_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetric',
            name='calories_consumed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories consumed in kcal'),
        ),
    ]
